import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import Navbar from "@/components/Layout/Navbar";
import { AuthProvider } from "@/components/Authentication/Provider/AuthProvider";
import AuthInitTrigger from "@/components/Authentication/Provider/AuthInitTrigger";
import AppProviders from "./providers";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <AppProviders>
          <AuthProvider>
            {/* Initialize Auth Here */}
            <AuthInitTrigger />
            {/* Will be using redux tools for product sorting and handling.. since there is alot of update to states.*/}
            <Navbar />
            {children}


            {/* Where we add a footer */}


            {/* Global Toast Container */}
            <ToastContainer
              position="top-right"
              autoClose={2500}
              hideProgressBar={false}
            />
          </AuthProvider>
        </AppProviders>
      </body>
    </html>
  );
}
