import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import Navbar from "@/components/Layout/Navbar";
import { AuthProvider } from "@/components/Authentication/Provider/AuthProvider";
import AuthInitTrigger from "@/components/Authentication/Provider/AuthInitTrigger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* Initialize Auth Here */}
          <AuthInitTrigger />
          {/* Will be using redux tools for product sorting and handling.. since there is alot of update to states.*/}
          <Navbar />
          {children}


          {/* Where we add a footer */}


          {/* Global Toast Container */}
          <ToastContainer
            position="top-right"
            autoClose={2500}
            hideProgressBar={false}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
